// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/dx-dashboard/CommandCenter.tsx": () => import("../components/mockups/dx-dashboard/CommandCenter.tsx"),
  "./components/mockups/dx-dashboard/DailyNarrative.tsx": () => import("../components/mockups/dx-dashboard/DailyNarrative.tsx"),
  "./components/mockups/dx-dashboard/FocusMode.tsx": () => import("../components/mockups/dx-dashboard/FocusMode.tsx"),
  "./components/mockups/dx-dashboard/TaskFeed.tsx": () => import("../components/mockups/dx-dashboard/TaskFeed.tsx")
};
